---
name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  publish-to-registry:
    name: Publish to Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: docker.pkg.github.com
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_with_latest: true
