---
name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  publish-to-registry:
    name: Publish to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate Tag List
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/namespace-operator
          tags: |
            type=ref,event=tag
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            ${{ steps.meta.outputs.tags }}
